### PR TITLE
Ejhumphrey/ack

### PR DESCRIPTION
**Pull request by ejhumphrey**
updates readme for #27 and adds an acknowledgements file (to be included in the TGZ archive)

### CODE REVIEW

**Comment by simondurand** [comment]
Tried to follow the instructions. And then when I tried to run
`./scripts/featurefy.py --file /some/audio/file.wav ./output_dir`
I got this error message:
`Did you forget to run ./scripts/download-deps.sh?`
I am then wondering if the instructions are enough.

**Comment by simondurand** [comment]
To give some details on the issue. I created a new miniconda py3.6 env to test it, and the issue is probably a path one related to this.

When I run `./scripts/download-deps.sh`, the VGGish model is downloaded in the `./openmic/vggish/__model__` folder. However, when I run afterwards `pip install .`, the `openmic` package is getting put in `~/miniconda2/envs/py36/lib/python3.6/site-packages/openmic/vggish/`, without the `__model__` folder. Then the `featurefy.py` script gets confused.

If I manually copy the `__model__` folder in `~/miniconda2/envs/py36/lib/python3.6/site-packages/openmic/vggish/`, the `featurefy.py` script works well.

Is there a way not to have to copy the VGGish model on your conda env site-package that could be written in the instruction README? Or should we just acknowledge to be careful when using a virtual environment?

**Comment by bmcfee** [comment]
Interesting.  I'd say this is probably not great style -- `__FOO__` is generally reserved in python for built-ins like `repr` or `init`.  Is it too late in the game to switch that up to `__model` (or `_model` would be better, since it communicates privacy without potentially going through namespace mangling)?

**Comment by ejhumphrey** [comment]
update from a sidebar: the paths in the setup file's package data were found to be erroneous (thanks @bmcfee), fixing on this issue since it came up as part of issues with installation instructions.

**Comment by ejhumphrey** [comment]
build is fine for 2.7/3.5/3.6, have disabled 3.4 and documented (somewhat) in #30

**Pull request merged**
